name: Deploy to Server

on:
  push:
    branches:
      - main  # Listen for commits to the main branch

jobs:
  deploy:
    runs-on: ubuntu-latest  # Use the Ubuntu environment provided by GitHub Actions

    steps:
      # Check out the code
      - name: Checkout code
        uses: actions/checkout@v3

      # Set up SSH key
      - name: Set up SSH
        uses: webfactory/ssh-agent@v0.5.3
        with:
          ssh-private-key: ${{ secrets.SGSVR }}  # Use the private key from GitHub Secrets

      # Verify if the SSH key is loaded
      - name: Verify SSH key
        run: ssh-add -L

      # Connect to the remote server and execute commands
      - name: Pull latest code and restart server
        run: |
          ssh -o StrictHostKeyChecking=no root@164.152.167.71 << 'EOF'
            echo "Entering project directory..."
            cd /opt/soundOfNovels/NovelsAdmin || exit 1

            echo "Pulling the latest code..."
            git pull
            # git fetch main main
            # git reset --hard main/main

            echo "Restarting the service..."
            ./autobot.sh restart  # Restart service script

            echo "Deployment completed!"
          EOF